package edu.northeastern.cs7580.cicd.pipelinelib.internal.service;

import edu.northeastern.cs7580.cicd.pipelinelib.exception.ValidationException;
import edu.northeastern.cs7580.cicd.pipelinelib.internal.parser.PositionAwareYamlParser;
import edu.northeastern.cs7580.cicd.pipelinelib.internal.parser.PositionAwareYamlParser.Position;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import lombok.Data;

/**
 * Collects validation errors during pipeline configuration validation.
 *
 * <p>This collector allows multiple validation errors to be accumulated
 * before throwing a single exception containing all error details. This
 * provides a better developer experience by showing all issues at once
 * rather than requiring multiple validation runs to discover all problems.
 *
 * <p>Errors are formatted in an IDE-friendly format that includes file path,
 * line number, column number, and descriptive message:
 * {@code filename:line:column: ERROR, message}
 *
 * <p>Example usage:
 * <blockquote><pre>
 *     ValidationErrorCollector collector = new ValidationErrorCollector(filePath);
 *
 *     if (someCondition) {
 *         collector.addError(5, 10, "Invalid value");
 *     }
 *
 *     if (anotherCondition) {
 *         Position pos = parser.getValuePosition("pipeline.name");
 *         collector.addError(pos, "Missing required field");
 *     }
 *
 *     collector.throwIfHasErrors(); // Throws if any errors collected
 * </pre></blockquote>
 *
 * <p>The collector supports three methods for adding errors:
 * <ul>
 *   <li>{@code addError(int, int, String)}: With explicit line and column</li>
 *   <li>{@code addError(Position, String)}: Using a Position object from the parser</li>
 *   <li>{@code addError(String)}: Without location (defaults to 0:0)</li>
 * </ul>
 *
 * <p>When multiple errors are collected, they are formatted as a multi-line
 * string with each error on its own line, maintaining the order in which they
 * were added.
 *
 * <p>Unless otherwise noted, passing a {@code null} argument to methods in
 * this class will cause a {@link NullPointerException} to be thrown.
 *
 * @implNote This collector is not thread-safe. Each validator should use its
 *     own collector instance during a validation pass. The collector maintains
 *     insertion order to ensure errors are reported in the sequence they were
 *     discovered during validation.
 * @see ValidationError
 * @see ValidationException
 * @see PositionAwareYamlParser
 * @see PositionAwareYamlParser.Position
 */
@Data
public class ValidationErrorCollector {
  /**
   * The path to the file being validated.
   *
   * <p>This path is used as the filename in all error messages generated by
   * this collector. It represents the source file where validation errors
   * were detected.
   */
  private final Path filePath;

  /**
   * The list of validation errors collected during validation.
   *
   * <p>Errors are stored in the order they are added, preserving the sequence
   * in which validation issues were discovered. The list grows as validation
   * proceeds, accumulating all errors before they are formatted and thrown
   * together.
   */
  private final List<ValidationError> errors = new ArrayList<>();

  public ValidationErrorCollector(Path filePath) {
    this.filePath = filePath;
  }

  /**
   * Adds a validation error with specific line and column information.
   *
   * <p>This method creates a new {@link ValidationError} with the provided
   * location and message, adding it to the internal error collection. The
   * filename is automatically set from the collector's file path.
   *
   * <p>Line and column numbers should be 1-indexed to match editor conventions.
   * Use 0 for either value when the specific position is unknown.
   *
   * @param line the line number where the error occurred (1-indexed)
   * @param column the column number where the error occurred (1-indexed)
   * @param message the descriptive error message
   */
  public void addError(int line, int column, String message) {
    errors.add(ValidationError.builder()
        .filename(filePath.toString())
        .line(line)
        .column(column)
        .message(message)
        .build());
  }

  /**
   * Adds a validation error using a Position object from the parser.
   *
   * <p>This is the preferred method when position information is available from
   * {@link PositionAwareYamlParser}. If the position is {@code null}, the error
   * is recorded with line and column set to 0.
   *
   * @param position the position where the error occurred, or {@code null} for unknown
   * @param message  the descriptive error message
   */
  public void addError(Position position, String message) {
    if (position != null) {
      addError(position.getLine(), position.getColumn(), message);
    } else {
      addError(0, 0, message);
    }
  }

  /**
   * Adds a validation error without specific location information.
   *
   * <p>This method is used when the error is general to the file or when position
   * tracking is not available. The error is recorded with both line and column
   * set to 0 to indicate unknown location.
   *
   * @param message the descriptive error message
   */
  public void addError(String message) {
    // For errors without specific location
    addError(0, 0, message);
  }

  /**
   * Checks whether any errors have been collected.
   *
   * <p>This method allows validators to check for errors before deciding whether
   * to continue with subsequent validation steps.
   *
   * @return {@code true} if at least one error has been collected, {@code false} otherwise
   */
  public boolean hasErrors() {
    return !errors.isEmpty();
  }

  /**
   * Throws a ValidationException if any errors have been collected.
   *
   * <p>This method is typically called after all validation steps complete to
   * aggregate and report all collected errors. The exception message contains
   * all errors formatted as a multi-line string, with each error on its own line
   * in the format: {@code filename:line:column: ERROR, message}
   *
   * <p>If no errors have been collected, this method does nothing.
   *
   * @throws ValidationException if one or more errors have been collected
   */
  public void throwIfHasErrors() {
    if (hasErrors()) {
      throw new ValidationException(formatErrors());
    }
  }

  /**
   * Formats all collected errors into a single multi-line string.
   *
   * <p>Each error is formatted on its own line using the IDE-friendly format:
   * {@code filename:line:column: ERROR, message}
   *
   * <p>Errors are formatted in the order they were collected, preserving the
   * sequence in which validation issues were discovered.
   *
   * @return a formatted string containing all errors, with newlines between errors
   */
  private String formatErrors() {
    return errors.stream()
        .map(e -> String.format("%s:%d:%d: ERROR, %s",
            e.getFilename(), e.getLine(), e.getColumn(), e.getMessage()))
        .collect(Collectors.joining("\n"));
  }

  /**
   * Returns a defensive copy of all collected errors.
   *
   * <p>The returned list is a snapshot of errors at the time of this call.
   * Subsequent additions to the collector will not affect the returned list.
   *
   * @return a new list containing all validation errors
   */
  public List<ValidationError> getErrors() {
    return new ArrayList<>(errors);
  }

}
