package edu.northeastern.cs7580.cicd.executionservice.dto;

import edu.northeastern.cs7580.cicd.executionservice.model.ExecutionStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response object returned after initiating a pipeline execution.
 *
 * <p>This DTO is returned to the API Gateway (and ultimately the CLI) after
 * processing a pipeline execution request. It contains metadata about the
 * execution including a unique identifier, run number, status, and any
 * relevant messages.
 *
 * <p><b>Response Status Values:</b>
 * <ul>
 *   <li>{@link ExecutionStatus#SUCCESS} — all jobs completed successfully</li>
 *   <li>{@link ExecutionStatus#FAILED} — one or more jobs failed</li>
 *   <li>{@link ExecutionStatus#VALIDATION_FAILED} — pipeline configuration is invalid</li>
 * </ul>
 *
 * @see ExecutionStatus
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PipelineExecutionResponse {

  /**
   * Unique identifier for this pipeline execution.
   *
   * <p>This UUID is generated by the Execution Service and can be used to
   * query execution status and results, link executions to logs and artifacts,
   * and correlate related events in monitoring systems.
   *
   * <p>Example: {@code "a1b2c3d4-e5f6-7890-abcd-ef1234567890"}
   */
  private String executionId;

  /**
   * Name of the pipeline that was executed.
   *
   * <p>Example: {@code "default"}, {@code "release-prod"}
   */
  private String pipelineName;

  /**
   * Sequential run number for this pipeline, scoped per pipeline.
   *
   * <p>Assigned by a PostgreSQL trigger on INSERT and increments per pipeline.
   * Returns {@code 0} if execution failed before the DB record was created
   * (e.g. validation errors).
   *
   * <p>Example: {@code 42}
   */
  private Integer runNumber;

  /**
   * Outcome of the pipeline execution.
   *
   * <p>Jackson serializes this enum to its {@link Enum#name()} value,
   * so the JSON response contains a string such as {@code "SUCCESS"}.
   *
   * @see ExecutionStatus
   */
  private ExecutionStatus status;

  /**
   * Human-readable message about the execution outcome.
   *
   * <p>Examples:
   * <ul>
   *   <li>{@code "Pipeline completed successfully. All 5 jobs passed."}</li>
   *   <li>{@code "Pipeline failed at job 'test'"}</li>
   *   <li>{@code "Pipeline validation failed: Circular dependency detected"}</li>
   * </ul>
   */
  private String message;
}