package edu.northeastern.cs7580.cicd.pipelinelib.model;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import lombok.Builder;
import lombok.Data;

/**
 * The {@code ExecutionPlan} class represents the complete execution plan for
 * a CI/CD pipeline. All execution plan representations generated by the dry-run
 * feature are instances of this class.
 *
 * <p>An execution plan organizes a validated pipeline into an ordered sequence
 * of stages, where each stage contains its jobs arranged according to their
 * dependencies. This structure provides a clear preview of how the pipeline
 * would execute without actually running it.
 *
 * <p>Here are some examples of how execution plans can be used:
 * <blockquote><pre>
 *     ExecutionPlan plan = ExecutionPlan.builder()
 *         .stages(stageExecutions)
 *         .build();
 *
 *     for (StageExecution stage : plan.getStages()) {
 *         System.out.println("Stage: " + stage.getStageName());
 *         for (Job job : stage.getJobs()) {
 *             System.out.println("  - " + job.getName());
 *         }
 *     }
 * </pre></blockquote>
 *
 * <p>The class {@code ExecutionPlan} serves as a container for stage executions,
 * maintaining the order in which stages should execute. Jobs within each stage
 * are topologically sorted to respect dependency constraints declared through
 * the {@code needs} keyword.
 *
 * <p>Execution plans are typically created by ExecutionPlanBuilder from
 * validated {@link Pipeline} objects. The builder ensures that all jobs are
 * properly ordered within their stages and that the stage sequence follows the
 * pipeline's stage definitions.
 *
 * <p>Unless otherwise noted, passing a {@code null} value for required
 * fields will result in a {@link NullPointerException}.
 *
 * @implNote This class is immutable and uses Lombok's {@code @Builder} pattern
 *     for construction. All fields are final and the stages list should be
 *     treated as read-only to maintain immutability guarantees.
 */
@Data
@Builder
public class ExecutionPlan {

  /**
   * The ordered list of stage executions in this pipeline.
   *
   * <p>Stages are ordered according to the pipeline's stage definitions,
   * with each stage containing its jobs in dependency order. This list
   * represents the complete execution flow of the pipeline from start
   * to finish.
   *
   * <p>Jobs can be extracted in topological order by flattening all jobs
   * from all stages, as each stage's job list is already topologically sorted.
   *
   * @see StageExecution
   * @see StageExecution#getJobs()
   */
  private final List<StageExecution> stages;

  /**
   * Pipeline-level dependency map: job name → list of job names it depends on.
   *
   * <p>This map tracks all job dependencies across the entire pipeline to enable
   * parallel execution scheduling. A job is ready to execute when all jobs in its
   * dependency list have completed successfully.
   *
   * <p>Jobs with no dependencies have an empty list as their value. This is a
   * global view across all stages, as validation ensures dependencies are within
   * the same stage.
   *
   * <p>Example:
   * <blockquote><pre>
   * {
   *   "compile": [],
   *   "unit-test": ["compile"],
   *   "integration-test": ["compile"],
   *   "deploy": ["unit-test", "integration-test"]
   * }
   * </pre></blockquote>
   *
   * <p>For Sprint 3 (sequential execution), this map is not actively used but
   * is populated for future parallel execution support. Jobs can be executed
   * sequentially by flattening the stages list: {@code stages.stream()
   * .flatMap(stage -> stage.getJobs().stream()).collect(Collectors.toList())}.
   *
   * @see StageExecution#getJobs()
   */
  private final Map<String, List<String>> jobDependencies;

  /**
   * Returns an unmodifiable view of the stages list.
   *
   * @return an unmodifiable list of stages, or {@code null} if not set
   */
  public List<StageExecution> getStages() {
    return stages == null ? null : Collections.unmodifiableList(stages);
  }

  /**
   * Returns an unmodifiable view of the job dependencies map.
   *
   * @return an unmodifiable map of job dependencies, or {@code null} if not set
   */
  public Map<String, List<String>> getJobDependencies() {
    return jobDependencies == null ? null : Collections.unmodifiableMap(jobDependencies);
  }

}
