{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: grafana
    {{- include "cicd-system.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus:9090
        isDefault: true
        editable: false
      - name: Loki
        type: loki
        uid: loki
        url: http://loki:3100
        editable: false
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo:3200
        editable: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            filterByTraceID: true
          tracesToMetrics:
            datasourceUid: prometheus
          serviceMap:
            datasourceUid: prometheus
          lokiSearch:
            datasourceUid: loki
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        options:
          path: /etc/grafana/provisioning/dashboards/json
{{- end }}
