apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    {{- include "cicd-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  selector:
    app: api-gateway
  ports:
    - name: http
      port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.port }}
