{{- if .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app: loki
    {{- include "cicd-system.labels" . | nindent 4 }}
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
{{- end }}
