{{- if .Values.postgres.enabled }}
# Placeholder values - replace with real secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "cicd-system.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password }}
{{- end }}
