apiVersion: v1
kind: Secret
metadata:
  name: cicd-db-credentials
  labels:
    {{- include "cicd-system.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.postgres.credentials.user }}
  DB_PASSWORD: {{ .Values.postgres.credentials.password }}
