apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  labels:
    app: report-service
    {{- include "cicd-system.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for postgres:5432...";
              until nc -z postgres 5432; do
                sleep 2;
              done
      containers:
        - name: report-service
          image: {{ .Values.image.repository }}/report-service:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: cicd-config
            - secretRef:
                name: cicd-db-credentials
          resources:
            {{- toYaml .Values.resources.stateless.reportService | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 20
